language: python
sudo: required
services:
- docker

python:
- "3.6"

install:
- pip install bugzoo

script:
- bugzoo source add https://github.com/ChrisTimperley/ManyBugs
- bugzoo bug validate manybugs:python:69368-69372
- bugzoo bug validate manybugs:python:69223-69224
